"""add picks table

Revision ID: 2899bca7341d
Revises: 45b47a419efe
Create Date: 2026-09-17 09:47:36.121691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2899bca7341d'
down_revision: Union[str, Sequence[str], None] = '45b47a419efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(length=200), nullable=False),
    sa.Column('away_team', sa.String(length=200), nullable=False),
    sa.Column('combo_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('leg_a_selection', sa.String(length=50), nullable=False),
    sa.Column('leg_b_selection', sa.String(length=50), nullable=False),
    sa.Column('favorite_side', sa.String(length=10), nullable=False),
    sa.Column('odds_leg_a', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('odds_leg_b', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('stake_leg_a', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stake_leg_b', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_stake', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('implied_hit_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('breakeven_prob', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('estimated_ev_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('home_score_actual', sa.Integer(), nullable=True),
    sa.Column('away_score_actual', sa.Integer(), nullable=True),
    sa.Column('outcome_scenario', sa.String(length=50), nullable=True),
    sa.Column('actual_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hit', sa.Boolean(), nullable=True),
    sa.Column('telegram_sent', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picks')
    # ### end Alembic commands ###
