"""init schema

Revision ID: 97cd275e5b3c
Revises: 
Create Date: 2026-09-16 22:58:54.634223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97cd275e5b3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('home_team', sa.String(length=200), nullable=False),
    sa.Column('away_team', sa.String(length=200), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('line', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('bookmaker', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('leg_a_market_id', sa.Integer(), nullable=True),
    sa.Column('leg_a_selection', sa.String(length=50), nullable=True),
    sa.Column('leg_b_market_id', sa.Integer(), nullable=True),
    sa.Column('leg_b_selection', sa.String(length=50), nullable=True),
    sa.Column('combo_type', sa.String(length=50), nullable=True),
    sa.Column('implied_hit_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('breakeven_prob', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('estimated_ev_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('stake_leg_a', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stake_leg_b', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_stake', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leg_a_market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['leg_b_market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('selection', sa.String(length=50), nullable=False),
    sa.Column('decimal_odds', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fixtures_kickoff', 'fixtures', ['kickoff_utc'])
    op.create_index('idx_markets_fixture', 'markets', ['fixture_id'])
    op.create_index('idx_odds_market', 'odds', ['market_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_odds_market', table_name='odds')
    op.drop_index('idx_markets_fixture', table_name='markets')
    op.drop_index('idx_fixtures_kickoff', table_name='fixtures')
    op.drop_table('odds')
    op.drop_table('combo_recommendations')
    op.drop_table('markets')
    op.drop_table('fixtures')
    # ### end Alembic commands ###
